[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "filenamingapi"
version = "0.1.0"
description = "Filename validators & parsers for EO products (Sentinel, Landsat, )"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
filenamingapi = ["schemas/**/*.json"]

[project.scripts]
filenaming-parse = "filenamingapi.cli:main"
